# Load Libraries

In [4]:
# import awswrangler as wr
import pandas as pd
# from credentials import AWS_PATH

In [5]:
# df = wr.s3.read_csv(AWS_PATH)
# df.head()

# Temporary file read, until we get AWS sorted out
df = pd.read_csv("data/nfl_sentiment_2025.csv")
df.head()

,player_id,player_name,player_first_name,player_last_name,player_position,team_abbreviation,game_id,bta_game_id,game_week,game_start_time,...,stats_receiving_rec_yards,stats_receiving_rec_td,stats_tackles_tackle_total,stats_tackles_sacks,stats_interceptions_interceptions,stats_interceptions_passes_defended,stats_fumbles_fum_forced,total_touches,total_opportunities,fantasy_points_ppr
0,6644.0,Charley Hughlett,Charley,Hughlett,LS,PHI,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,7229.0,Dante Fowler,Dante,Fowler,DE,DAL,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7268.0,Bryan Anger,Bryan,Anger,P,DAL,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,8047.0,Lane Johnson,Lane,Johnson,T,PHI,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,8112.0,C.J. Goodwin,C.J.,Goodwin,CB,DAL,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Data Cleaning and Validation

In [6]:
for col in df.columns:
    print(col + ": " + str(df[col].isnull().sum()))

player_id: 0
player_name: 0
player_first_name: 0
player_last_name: 0
player_position: 0
team_abbreviation: 0
game_id: 0
bta_game_id: 0
game_week: 0
game_start_time: 0
opp_offense_dvoa: 0
opp_defense_dvoa: 0
stats_snap_counts_offense_snaps: 0
stats_passing_pass_attempts: 11112
stats_passing_pass_completions: 11112
stats_passing_pass_yards: 11112
stats_passing_pass_td: 11112
stats_passing_pass_int: 11112
stats_passing_qb_rating: 11112
stats_rushing_rush_attempts: 10546
stats_rushing_rush_yards: 10546
stats_rushing_rush_td: 10546
stats_receiving_targets: 10546
stats_receiving_receptions: 10546
stats_receiving_rec_yards: 10546
stats_receiving_rec_td: 10546
stats_tackles_tackle_total: 0
stats_tackles_sacks: 0
stats_interceptions_interceptions: 0
stats_interceptions_passes_defended: 0
stats_fumbles_fum_forced: 0
total_touches: 0
total_opportunities: 0
fantasy_points_ppr: 0

In [7]:
# Check if nulls are in the same rows
print((df['stats_passing_pass_completions'].isnull() == df['stats_passing_pass_int'].isnull()).all())
print((df['stats_passing_pass_completions'].isnull() == df['stats_passing_pass_attempts'].isnull()).all())

print((df['stats_rushing_rush_yards'].isnull() == df['stats_receiving_rec_td'].isnull()).all())
print((df['stats_rushing_rush_yards'].isnull() == df['stats_rushing_rush_attempts'].isnull()).all())

True
True
True
True

In [8]:
# Check positions of nulls
print(df[df['stats_passing_pass_completions'].isnull()]['player_position'].unique())
print(df[df['stats_rushing_rush_yards'].isnull()]['player_position'].unique())

# All of the nulls are linemen or defense, so this is expected

['LS' 'P' 'T' 'CB' 'K' 'FS' 'OT' 'OLB' 'ILB' 'G' 'C' 'NT' 'MLB' 'SS']
['P' 'T' 'CB' 'K' 'FS' 'OT' 'OLB' 'ILB' 'G' 'C' 'NT' 'MLB' 'SS']

## Fill NaNs with Zeroes

In [9]:
df.fillna(0, inplace=True)
df.head()

,player_id,player_name,player_first_name,player_last_name,player_position,team_abbreviation,game_id,bta_game_id,game_week,game_start_time,...,stats_receiving_rec_yards,stats_receiving_rec_td,stats_tackles_tackle_total,stats_tackles_sacks,stats_interceptions_interceptions,stats_interceptions_passes_defended,stats_fumbles_fum_forced,total_touches,total_opportunities,fantasy_points_ppr
0,6644.0,Charley Hughlett,Charley,Hughlett,LS,PHI,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,7229.0,Dante Fowler,Dante,Fowler,DE,DAL,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7268.0,Bryan Anger,Bryan,Anger,P,DAL,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,8047.0,Lane Johnson,Lane,Johnson,T,PHI,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,8112.0,C.J. Goodwin,C.J.,Goodwin,CB,DAL,148741.0,2025.09.04.PHI.DAL,1.0,2025-09-05 00:20:00+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Check if columns are integers

In [10]:
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns.tolist()
# print(numeric_cols)

int_inds = []

for col in numeric_cols:
    print(str(col) + ": " + str((df[col] % 1 == 0).all()))
    int_inds.append((df[col] % 1 == 0).all())

int_cols = [col for col, is_int in zip(numeric_cols, int_inds) if is_int]

player_id: True
game_id: True
game_week: True
opp_offense_dvoa: False
opp_defense_dvoa: False
stats_snap_counts_offense_snaps: True
stats_passing_pass_attempts: True
stats_passing_pass_completions: True
stats_passing_pass_yards: True
stats_passing_pass_td: True
stats_passing_pass_int: True
stats_passing_qb_rating: False
stats_rushing_rush_attempts: True
stats_rushing_rush_yards: True
stats_rushing_rush_td: True
stats_receiving_targets: True
stats_receiving_receptions: True
stats_receiving_rec_yards: True
stats_receiving_rec_td: True
stats_tackles_tackle_total: True
stats_tackles_sacks: False
stats_interceptions_interceptions: True
stats_interceptions_passes_defended: True
stats_fumbles_fum_forced: True
total_touches: True
total_opportunities: True
fantasy_points_ppr: False

In [11]:
# Convert appropriate columns to int64
for col in int_cols:
    df[col] = df[col].astype('int64')

## Verify values are positive

In [12]:
positive_cols = numeric_cols.copy()
positive_cols.remove('opp_offense_dvoa')
positive_cols.remove('opp_defense_dvoa')
positive_cols.remove('stats_passing_pass_yards')
positive_cols.remove('stats_rushing_rush_yards')
positive_cols.remove('stats_receiving_rec_yards')
positive_cols.remove('fantasy_points_ppr')


for col in positive_cols:
    print(str(col) + ": " + str((df[col] >= 0).all()))

player_id: True
game_id: True
game_week: True
stats_snap_counts_offense_snaps: True
stats_passing_pass_attempts: True
stats_passing_pass_completions: True
stats_passing_pass_td: True
stats_passing_pass_int: True
stats_passing_qb_rating: True
stats_rushing_rush_attempts: True
stats_rushing_rush_td: True
stats_receiving_targets: True
stats_receiving_receptions: True
stats_receiving_rec_td: True
stats_tackles_tackle_total: True
stats_tackles_sacks: True
stats_interceptions_interceptions: True
stats_interceptions_passes_defended: True
stats_fumbles_fum_forced: True
total_touches: True
total_opportunities: True

## Convert game start time to time objects

In [13]:
print(df['game_start_time'].dtype)
df['game_start_time'] = pd.to_datetime(df['game_start_time'])
print(df['game_start_time'].dtype)

object
datetime64[ns, UTC]

In [14]:
df.head()

,player_id,player_name,player_first_name,player_last_name,player_position,team_abbreviation,game_id,bta_game_id,game_week,game_start_time,...,stats_receiving_rec_yards,stats_receiving_rec_td,stats_tackles_tackle_total,stats_tackles_sacks,stats_interceptions_interceptions,stats_interceptions_passes_defended,stats_fumbles_fum_forced,total_touches,total_opportunities,fantasy_points_ppr
0,6644,Charley Hughlett,Charley,Hughlett,LS,PHI,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00:00,...,0,0,0,0.0,0,0,0,0,0,0.0
1,7229,Dante Fowler,Dante,Fowler,DE,DAL,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00:00,...,0,0,0,0.0,0,0,0,0,0,0.0
2,7268,Bryan Anger,Bryan,Anger,P,DAL,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00:00,...,0,0,0,0.0,0,0,0,0,0,0.0
3,8047,Lane Johnson,Lane,Johnson,T,PHI,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00:00,...,0,0,0,0.0,0,0,0,0,0,0.0
4,8112,C.J. Goodwin,C.J.,Goodwin,CB,DAL,148741,2025.09.04.PHI.DAL,1,2025-09-05 00:20:00+00:00,...,0,0,0,0.0,0,0,0,0,0,0.0

# Verify IDs are consistent

In [15]:
def check_consistent_columns(df, col1, col2):
    if (df[col1].isnull() != df[col2].isnull()).any():
        return f"{col1} and {col2} have NOT nulls in the same rows."

    # Get unique pairs of values from the two columns, ignoring nulls
    unique_pairs = df[[col1, col2]].dropna().drop_duplicates()

    # Check if we have an equal number of unique pairs and unique values in col1
    # If not, one key in col1 maps to multiple values in col2, which is inconsistent
    return (len(unique_pairs) == unique_pairs[col1].nunique())

In [24]:
# Check consistencies between columns
print('game_id and bta_game_id are consistent:', check_consistent_columns(df, 'game_id', 'bta_game_id'))
print('game_id and game_start_time are consistent:', check_consistent_columns(df, 'game_id', 'game_start_time'))
print('player_id and player_name are consistent:', check_consistent_columns(df, 'player_id', 'player_name'))
print('player_id and player_first_name are consistent:', check_consistent_columns(df, 'player_id', 'player_first_name'))
print('player_id and player_last_name are consistent:', check_consistent_columns(df, 'player_id', 'player_last_name'))
print('player_id and player_position are consistent:', check_consistent_columns(df, 'player_id', 'player_position'))

game_id and bta_game_id are consistent: True
game_id and game_start_time are consistent: True
player_id and player_name are consistent: True
player_id and player_first_name are consistent: True
player_id and player_last_name are consistent: True
player_id and player_position are consistent: False

In [ ]:
agg_df = df.groupby('player_id')['player_position'].nunique()
non_unique_players = agg_df[agg_df > 1].index.tolist()
# print("Players with multiple positions:", non_unique_players)

Players with multiple positions: [6160, 6426, 6696, 6887, 6963, 7523, 7640, 7784, 7876, 8153, 8801, 9675, 9863, 9942, 10027, 12748, 12763, 12988, 13055, 13258, 13484, 14500, 14503, 14504, 14974, 14981, 14992, 14993, 15031, 15060, 15075, 15243, 15244, 15371, 16131, 16520, 16587, 16653, 16720, 16914, 18569, 18652, 18654, 18796, 19032, 24081, 30188, 30299, 30327, 30602, 30822, 30981, 33541, 33544, 39112, 39217, 39226, 39274, 39442, 47385, 47841, 48027, 79794, 79802, 79808, 108836, 108856, 108862, 111940, 112096, 112175, 112296, 112334, 112359, 133855, 133929, 133968, 133982, 133990, 133991, 134010, 134023, 134033, 134051, 134285, 134362, 166641, 166649, 166678, 166704, 166759, 166789, 166831, 166867, 166880, 167686, 167707, 167740, 167823, 167844]

In [23]:
dup_position_df = df[df['player_id'].isin(non_unique_players)][['player_id', 'player_position']].drop_duplicates()
dup_position_df.sort_values('player_id', inplace=True)
print(dup_position_df)

       player_id player_position
3107        6160              DE
2636        6160             OLB
194         6426              NT
9717        6426              DT
937         6696              DE
...          ...             ...
917       167740              DE
19218     167823              LB
11222     167823             ILB
5757      167844              DB
2728      167844              FS

[200 rows x 2 columns]

For the most part, duplicate listings of positions seems fairly reasonable

Nothing that seems out of the ordinary

# Save to new .csv() file

In [12]:
df.to_csv("data/nfl_sentiment_2025_cleaned.csv", index=False)